### ISSUE TITLE
SyntaxError: Invalid or unexpected token (line:3)

### ISSUE THREAD

**Issue by stefan242** [DaveMDS/node-red-contrib-tasmota#12]
I cannot use the three tasmota nodes anymore. Even after removing and reinstalling I'm getting these errors:

16 May 14:20:00 - [info] Installiertes Modul: node-red-contrib-tasmota
16 May 14:20:00 - [info] Hinzugefügte Node-Typen:
16 May 14:20:00 - [info]  - node-red-contrib-tasmota:Tasmota Switch : SyntaxError: Invalid or unexpected token (line:3)
16 May 14:20:00 - [info]  - node-red-contrib-tasmota:Tasmota Sensor : SyntaxError: Invalid or unexpected token (line:3)
16 May 14:20:00 - [info]  - node-red-contrib-tasmota:Tasmota Light : SyntaxError: Invalid or unexpected token (line:3)

**Comment by DaveMDS** [comment]
I need more info to help you...
node-red version?
what has changed since the node stop working?

**Comment by stefan242** [comment]
Hi Dave,

> Reply to this email directly, view it on GitHub, ...

Which method do you prefer?


> I need more info to help you...> node-red version?> what has changed since the node stop working?
I am an IT pro, so I know the sentence "what has changed since ..." ;-)

It was only the update of two tasmota plugs to firmware 8.3.0.
All other plugs all still firmware 8.2.0. I pulled both plugs, but no
difference.


17 May 09:52:35 - [info] Node-RED Version: v1.0.6
17 May 09:52:35 - [info] Node.js  Version: v12.16.2
17 May 09:52:35 - [info] Linux 5.4.35-v7+ arm LE
17 May 09:52:36 - [info] Paletten-Nodes werden geladen
17 May 09:52:46 - [info] Dashboard version 2.22.1 started at /ui
17 May 09:52:47 - [warn] --------------------------------------------
17 May 09:52:47 - [warn] [node-red-contrib-tasmota/Tasmota switch]
SyntaxError: Invalid or unexpected token
17 May 09:52:47 - [warn] [node-red-contrib-tasmota/Tasmota sensor]
SyntaxError: Invalid or unexpected token
17 May 09:52:47 - [warn] [node-red-contrib-tasmota/Tasmota light]
SyntaxError: Invalid or unexpected token

I already started a node-red forum discussion here:

https://discourse.nodered.org/t/tasmota-node-not-working-after-tasmota-8-30-firmware-update/26740/11

There I wrote:

But since zigbee2mqtt gets the same error when installing or running:
[...]
...I will dive into the mqtt node, which both seems to use.



-- 
Stefan Braunstein
________________________________________________
Braunstein IT-Service  |       www.braunstein.de
D-77694 Kehl/Rhein     |       www.sme-server.de
Tel: 07853 - 97991     |   www.netware-server.de

**Comment by DaveMDS** [comment]
Any news on this one?
reading the forum discussion seems the problem is in the enocean node
can this issue be closed?
