### ISSUE TITLE
Using Variables in the Node Field в Seting -  Device

### ISSUE THREAD

**Issue by odis68** [DaveMDS/node-red-contrib-tasmota#14]
it is also possible to use variable values in the node settings field !!!

![изображение](https://user-images.githubusercontent.com/46837765/86126150-7ff18300-bae6-11ea-983f-b8e4137c3591.png)

**Comment by DaveMDS** [comment]
Hi, is this a feature request?
What kind of variables you need to use in the config?

**Comment by odis68** [comment]
Field "Device"

**Comment by DaveMDS** [comment]
hi, sadly what you want is too hard to implement, and IMO out of the scope of the nodes.
I think you can easily implement what you want using the standard MQTT node, where you can subscribe to topics using wildcards
