### ISSUE TITLE
[FEATURE REQUEST] - unplugged device / send this status

### ISSUE THREAD

**Issue by S474N** [DaveMDS/node-red-contrib-tasmota#15]
Have Sonoff Tasmota device. When I unplugged in from power outlet, there will be state in Nodered "Neaktivni" (Not active) with warn red square. But the node don't send this information. Is it possible to add this feature?

**Comment by DaveMDS** [comment]
Hi,
just enable the "Send enable/disable message" in the node config, 
then it will send a messagge on every LWT status changes (online/offline)

Hope this is what you are asking 
Best regards

**Comment by S474N** [comment]
Have checked all time. It will send via msg.payload or msg.status? Thanks for reply.

**Comment by DaveMDS** [comment]
it should be msg.enabled, or maybe just enabled, one of the 2, I don't remember well :)

**Comment by S474N** [comment]
msg.enabled is normal undefined, when unplug off, then is "false".

**Comment by DaveMDS** [comment]
{msg.enabled: true} is sent when the device goes online
{msg.enabled: false} is sent when the device goes offline (after a variable amount of seconds)

it works perfectly here

**Comment by S474N** [comment]
But there is another problem. It will send `{msg.enabled: false}` again and again when Deployed.

**Comment by DaveMDS** [comment]
hmm, this seems something wrong with your mqtt broker, or maybe the device itself.

The msg.enabled messagges are sent every time the node receive a tele/<device>/LWT messagge on mqtt,
the node just translate and forward the mqtt message to a node-red message. 

I suggest you try to add a standard mqtt-node to your flow and subscribe to tele/<device>/LWT to understand what is happening

**Comment by S474N** [comment]
Have absolutelly standard eclipse-mosquitto server as broker. 

Device is Sonoff RFR3 with Tasmota 8.5.0.1

In MQTT IN in nodered:
- if online payload is:
`{"topic":"tele/sonoff-rfr3-bazen/LWT","payload":"Aktivní","qos":0,"retain":true,"_topic":"tele/sonoff-rfr3-bazen/LWT","_msgid":"d684945b.611fa8"}`
- then offline:
`{"topic":"tele/sonoff-rfr3-bazen/LWT","payload":"Neaktivní","qos":1,"retain":false,"_topic":"tele/sonoff-rfr3-bazen/LWT","_msgid":"74d53ab3.cc2e84"}`
- and next online:
`{"topic":"tele/sonoff-rfr3-bazen/LWT","payload":"Aktivní","qos":0,"retain":false,"_topic":"tele/sonoff-rfr3-bazen/LWT","_msgid":"c50647d8.117778"}`

Tested also with MQTT.fw:
- subscribed to `tele/sonoff-rfr3-bazen/LWT`
- when is online, it has `Aktivní` (it mean's Active in English)
- next offline, it changed to `Neaktivní` (it mean's non-active in English)
- when is next online, it has `Aktivní` (it mean's Active in English)

**Comment by DaveMDS** [comment]
Ok, I understand the issue now !
The problem is that the node expect `Online/Offline` as the LWT payload, not `Aktivní/Neaktivní`

TBH it seems crazy to me that a protocol string is translated, there is no way for a controller to understand the LWT payload if it change between different languages.

Now the question is: why your tasmota behave different than mine? did you changed in some way the LWT payload?
or maybe you are using a translated release of Tasmota?

**Comment by S474N** [comment]
I'm using standard genuine Tasmota, but as you wrote - translated Czech version.

http://ota.tasmota.com/tasmota/
`tasmota-CZ.bin.gz | http://ota.tasmota.com/tasmota/tasmota-CZ.bin.gz | 424k | tasmota-CZ.bin | http://ota.tasmota.com/tasmota/tasmota-CZ.bin | 598k | 20200926 11:17
`

**Comment by DaveMDS** [comment]
Well, this seems to me a Tasmota issue, IMHO the LWT payload should always be `Online/Offline`, regardless of the user language. Protocols should never be translated!
It is not possible to add any possible language to the node code.

Can you please open an issue at Tasmota? Maybe they have already addressed this issue in the past or have any workaround

Of course you can just install the english Tasmota to your device to fix the issue

**Comment by S474N** [comment]
Tested flashing to original english Tasmota and everything is OK :)

But opened new issue at Tasmota:
https://github.com/arendst/Tasmota/issues/9395

**Comment by DaveMDS** [comment]
Great, lets see how it goes there
thanks for testing and reporting :)

**Comment by S474N** [comment]
So I made pull request with czech language file, but this is global problem of Tasmota also with another translations.

**Comment by DaveMDS** [comment]
Yep, I'm following the Tasmota issue you opened. 
Those 2 strings should not be translatable at all, I also voted for the last comment from Jason2866.

If you agree we can close this issue

**Comment by S474N** [comment]
Of course, thank you for cooperating!
