### ISSUE TITLE
How to use with Tasmota for Sonoff Zigbee Bridge?

### ISSUE THREAD

**Issue by derekoharrow** [DaveMDS/node-red-contrib-tasmota#16]
I've got the Sonoff ZB Bridge setup and using Tasmota. I can add devices to this from Tasmota and controlled them manually from MQTT, but it's a pain. I'd really like to use your Tasmota script to make this simpler via NodeRED.
The problem is that I cannot get your nodes to work properly with this setup. Here's a couple of examples of info being received from the bridge in msg.payload:

```
{"ZbReceived":{"0x11FE":{"Device":"0x11FE","Name":"DoorContact","Power":0,"Endpoint":1,"LinkQuality":179}}}
{"ZbReceived":{"0x0E3A":{"Device":"0x0E3A","Name":"Cabin_Button_2","MultiInValue":1,"Endpoint":1,"LinkQuality":129}}}
```
The first is a contact switch, and the second is a button. As you can see, the key differentiator is the device ID object at the very start. How would I code this in the Output Channels payload so I can distinguish and detect them correctly?

Similarly, how would I do the reverse to control a switch?

Thanks

**Comment by DaveMDS** [comment]
Hi, I don't know how the ZB Bridge works,
but I'm quite sure it is not compatible with this tasmota module

Of course patches to add this support are welcome :)

Best regards

**Comment by alsa-kode** [comment]
I might be getting the question the wrong way but... not sure what you're trying.
The 'tasmotised' ZB bridge works as a ZB gateway and to publish back and forth to MQTT server.
The tasmota wifi devices can be accessed either directly to their IP address or by sending them messages through mqtt.
Neither of these options is related to the zigbee bridge.

**Comment by DaveMDS** [comment]
Hi, the Sonoff ZB Bridge (tasmotized) is not supported by this node.
The MQTT messages are different from a normal tasmota device, thus there are currently no way to make it work with the bridge
