### ISSUE TITLE
Backlog payload with "command" topic doesn't work

### ISSUE THREAD

**Issue by rockstar2020** [DaveMDS/node-red-contrib-tasmota#17]
Hi @DaveMDS,
Thank you for your great work on Tasmota node.
I have a question.
I'm able to successfully execute single commands such as "POWER ON" using "command" topic but when I send multiple commands such as "Backlog POWER ON; Dimmer 20" the message that reaches Tasmota device is changed to "POWER OFF".
Can you confirm if Backlog command is supported in this node or not?

Many thanks in advance

**Comment by DaveMDS** [comment]
Hi,
you should be able to send more than one command using a **list** payload on the `command` topic, fe:
['POWER ON', 'Dimmer 20']

The docs has a bit more info, let me know if this works for you

**Comment by rockstar2020** [comment]
Thanks a lot @DaveMDS,
I did try your suggestion but the following payload with "command" topic didn't work.
Is there something wrong with the syntax?
{ topic: "command", payload: "['POWER ON', 'Dimmer 63']", _msgid: "23654274.7c706e" }

Many thanks in advance for your help

Cheers

**Comment by DaveMDS** [comment]
Yes, your syntax is wrong
your payload is a string, not a list, you must remove the `"` (double quote) around the payload

**Comment by rockstar2020** [comment]
Thanks but I'm injecting variables such as Dimmer value. Tried different formatting option but couldn't make it as a list.
I'm using functions to build the payload for me so don't know how I can inject a variable into a list payload.
I'll try again but if you know how to format it in functions node I appreciate if you could guide me.

Cheers
Mehdi

**Comment by DaveMDS** [comment]
in the function node something like:

`return {payload: ["POWER ON", "Dimmer 63"]}`

**Comment by rockstar2020** [comment]
Thanks @DaveMDS,
I managed to make it work using list variables.
Appreciate your help.

Cheers
