### ISSUE TITLE
An hyphen in output-channel definition causes a parsing error

### ISSUE THREAD

**Issue by Trym0** [DaveMDS/node-red-contrib-tasmota#18]
I am trying to use your Tasmota Sensor node with a sensor that has an hyphen in its name.
Mqqt In:

`{"topic":"tele/tasmota_45FABD/SENSOR","payload":"{\"Time\":\"2020-10-21T17:39:26\",\"SHT3X-0x44\":{\"Temperature\":17.1,\"Humidity\":71.6,\"DewPoint\":11.9},\"TempUnit\":\"C\"}","qos":0,"retain":false,"_topic":"tele/tasmota_45FABD/SENSOR","_msgid":"2799aa79.f26426"}`

Unfortunately, using 
`SHT3X-0x44.Temperature ` as an output-channel definition cause this error:

`{"code":"S0201","position":10,"token":"x44","stack":"Error\n    at handleError (/usr/lib/node_modules/node-red/node_modules/jsonata/jsonata.js:5925:30)\n    at parser (/usr/lib/node_modules/node-red/node_modules/jsonata/jsonata.js:6886:13)\n    at jsonata (/usr/lib/node_modules/node-red/node_modules/jsonata/jsonata.js:5420:19)\n    at Object.prepareJSONataExpression (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/util.js:571:16)\n    at TasmotaSensorNode.sendToOutputs (/home/nodered/.node-red/node_modules/node-red-contrib-tasmota/nodes/sensor.js:46:31)\n    at TasmotaSensorNode.onSensorStatus (/home/nodered/.node-red/node_modules/node-red-contrib-tasmota/nodes/sensor.js:67:14)\n    at Object.callback (/home/nodered/.node-red/node_modules/node-red-contrib-tasmota/nodes/sensor.js:20:14)\n    at MqttClient.<anonymous> (/home/nodered/.node-red/node_modules/node-red-contrib-tasmota/nodes/tasmota_mqtt_client.js:91:33)\n    at MqttClient.emit (events.js:327:22)\n    at MqttClient._handlePublish (/home/nodered/.node-red/node_modules/mqtt/l...","message":"Syntax error: \"x44\""}
`
The error disappears only when I remove the hyphen from the output-channel definition.

**Comment by DaveMDS** [comment]
Hi, at a first look seems that the issue is not the hyphen, but the string `0x44`, that is probably interpreted by JSONata as a special char. 
Can you please show me your node configuration?
I need to see the output expressions you entered in "Output channels payload"

**Comment by DaveMDS** [comment]
Ok, I reproduced the issue, 
I think you configured something like: `SHT3X-0x44.Temperature` for an output channel, right?
This is not a valid JSONata expression, you need to write it like: `"SHT3X-0x44".Temperature` and it works.

This is not a tasmota node issue, but just how JSONata expressions works ;)

Let me know if this fix your issue

**Comment by Trym0** [comment]
Thanks for the prompt answer.
Yes you're quite right, I was barking up the wrong tree pinning the errors on the hyphen :).  Your parentheses suggestion prevented the json parsing error while still producing the needed output

Thanks for the help and the otherwise excellent nodes.
