### ISSUE TITLE
Sensor Configured as Switch Not Reporting Status Result

### ISSUE THREAD

**Issue by Beormund** [DaveMDS/node-red-contrib-tasmota#19]
Thank you for node-red-contrib-tasmota. I have a [single relay module](http://www.chinalctech.com/cpzx/2/479.html) flashed with Tasmota. The single relay is successfully being controlled by your switch node and is reporting status fine via this node. 

I have a reed switch sensor connected to GPIO14 and it is configured as Switch2 in Tasmota. SetOption14 has been set to detach switches from relays. When I add your sensor node for the reed switch it only reports the switch's status from periodic telemetry:

`tele/tasmota_3DD57B/SENSOR = {"Time":"2020-12-09T14:12:09","Switch2":"OFF"} 
`

However, when the sensor closes and sends an immediate MQTT status update:

`stat/tasmota_3DD57B/RESULT = {"Switch2":{"Action":"ON"}})`

I can't get the sensor node to report this update in real-time. If I use your button node instead of a sensor node, then the node does report the immediate status update (albeit showing it as 'button2' in debug messages) but then doesn't report periodic telemetry. 

Is there something I am missing? I have left the nodes' advanced MQTT settings blank (i.e., default). Ive checked incoming MQTT payloads via a network mqtt in node and all looks correct. Thanks.

**Comment by DaveMDS** [comment]
Hi, 
as your sensor is configured as Switch2 in tasmota then the correct node to use should be the Button one.

What I do not understand is why you need telemetry from a button, the button node output a msg on every 
state change, thus you already have the latest state

can you please explain your use case and why you need telemetry from a button?

Dave

**Comment by Beormund** [comment]
Thanks for this. 

Is it the /RESULT suffix of the Switch2 configuration (which Tasmota outputs by default) that is causing problems for the sensor node? Intuitively it feels that my reed switch sensor should be handled by a sensor node rather than a button node. For me, realtime state changes are of more importance than telemetry for sensors, hence the expected behaviour of the sensor node prioritising the handling of realtime state changes over telemetry. It would be great if the sensor node could handle /RESULT in the MQTT topic path.

I have created a Tasmota rule to publish the MQTT message in the format that the sensor node expects and this now works fine.

`On Switch2#State Do Publish tele/tasmota_3DD57B/SENSOR {"Time":"%timestamp%","Switch2":%value%} ENDON`

Thank you for your help.

**Comment by Beormund** [comment]
This Tasmota rule also works well with your sensor node:

`On Switch2#State Do Status 8 ENDON`

which outputs:

`stat/tasmota_3DD57B/STATUS8 = {"StatusSNS":{"Time":"2020-12-09T18:45:27","Switch2":"OFF"}}`

**Comment by DaveMDS** [comment]
the sensor node it designed to handle sensors like temperature, humidity etc that do not provide realtime events.
reed sensors is handled in tasmota as switch (in fact you configured it as Switch2), thus the correct node to use should be the button one
