### ISSUE TITLE
Custom MQTT full topic

### ISSUE THREAD

**Issue by kumy** [DaveMDS/node-red-contrib-tasmota#2]
The Tasmota firmware/[documentation](https://tasmota.github.io/docs/#/MQTT?id=fulltopic) allow us to create full topics such as:
* `FullTopic %prefix%/%topic%/ default`
* `FullTopic tasmota/%topic%/%prefix%/`
* `FullTopic tasmota/bedroom/%topic%/%prefix%/`
* `FullTopic penthouse/bedroom1/bathroom2/%topic%/%prefix%/`
* `FullTopic %prefix%/home/cellar/%topic%/`

Unfortunately this node has only 2 predefined templates `%prefix%/%topic%/` `%topic%/%prefix%/`.

May you please allow us to define our custom `FullTopic` in advanced configuration?

Thanks :)

**Comment by kumy** [comment]
As a workaround I've overridden topic prefixes as:
`tasmota/bedroom/cmnd`
`tasmota/bedroom/stat`
`tasmota/bedroom/tele`

I hope it'll work

**Comment by DaveMDS** [comment]
Indeed, that config need to be a free string, and real susbstitution need to be done.
working on it right now...

**Comment by DaveMDS** [comment]
OK, I made a new release (0.9.1) that accept a free string as full-topic, in the same format as in Tasmota (replace "%topic%" and "%prefix%"), now I think you can now make any possible combination :)
Can you please update and test?

**Comment by kumy** [comment]
Seems to work nicely :) Thanks!!!

**Comment by DaveMDS** [comment]
Great ! Thanks for reporting and testing :)
