### ISSUE TITLE
Object Payload: Brightness and Color cannot be set at the same time

### ISSUE THREAD

**Issue by fpetry** [DaveMDS/node-red-contrib-tasmota#20]
When setting i.e. brightness (25) and color (blue) at the same time, it looks as if the brightness will be sent but directly overwritten by the color command, which sets brightness to 100%.

Node-red screenshot (test setup):

![grafik](https://user-images.githubusercontent.com/4649876/102713906-9e814b80-42cb-11eb-91bd-61dfa43d75f6.png)

Tasmota console output (setting brightness and color together):

~~~
14:00:33 MQT: tasmota/lightcat/stat/RESULT = {"POWER":"ON","Dimmer":25,"Color":"000040","HSBColor":"240,100,25","Channel":[0,0,25]}
14:00:33 MQT: tasmota/lightcat/stat/RESULT = {"POWER":"ON","Dimmer":100,"Color":"0000FF","HSBColor":"240,100,100","Channel":[0,0,100]}
~~~

Tasmota console output (setting color, then brightness):

~~~
14:02:17 MQT: tasmota/lightcat/stat/RESULT = {"POWER":"ON","Dimmer":100,"Color":"0000FF","HSBColor":"240,100,100","Channel":[0,0,100]}
14:02:20 MQT: tasmota/lightcat/stat/RESULT = {"POWER":"ON","Dimmer":25,"Color":"000040","HSBColor":"240,100,25","Channel":[0,0,25]}
~~~

In the source (/nodes/light.js, line 126ff.) the single attributes are handled sequentially, with brightness before color.

I would think that handling brightness after color would fix the issue. As I am not that into JS I did not test modifications to the JS code.

**Comment by hank2233** [comment]
Hey there,
found out, you could inject the string "0,10,20" as msg.payload.rgb to switch off Red and dim Green and Blue.
Could that work for you?

**Comment by DaveMDS** [comment]
Thanks for reporting !
