### ISSUE TITLE
Feature request: add msg.topic

### ISSUE THREAD

**Issue by soosp** [DaveMDS/node-red-contrib-tasmota#22]
Please add ability of set/forward msg.topic on the output of nodes. It make easier the process the outputs of sensor nodes (e.g. create charts to display and comapre data from more sensors etc.).

**Comment by DaveMDS** [comment]
Hi,
can you please explain better your use case please? You would like to have the full message forwarded or only the topic?

**Comment by soosp** [comment]
Imagine, that there are two or more temperature sensors, the Tasmota Sensor node sends the temperature data to Dasbors Chart (ui-chart) node. It identify the data series for curves and legends by msg.topic. So it would be good to make it possible to specify the topic in the Sensor node or forward the topic from the input (e.g. from an inject node) if the topic is not specified.

**Comment by soosp** [comment]
MQTT also use topic to handle messages.

**Comment by DaveMDS** [comment]
Hi, first of all sorry for the late reply!

I'm getting to this right now, but it does not seems so simple, at least in my use cases.
I could easily add an option in the Sensor node to specify the topic for the messages it send, but it would be the same for all configured outputs, and this is not probably what you want...

For example this is my normal use case (2 sensors read from the same device):
![SensorTopic](https://user-images.githubusercontent.com/52688/113503788-531a4280-9534-11eb-9c57-6a073669d5a9.png)

What should we do in this case? Should we provide the ability to choose a different topic for each configured output? (not so easy to implement, and will clutter the UI a bit)

**Comment by soosp** [comment]
Hi,
Thank you for thinking about problem. As I mention I use the topic to mark data in charts. Here is my planned scenario:
![Vágólap01](https://user-images.githubusercontent.com/24782682/113521467-e8035700-9599-11eb-97a2-ac92373f4cb2.jpg)
![Vágólap02](https://user-images.githubusercontent.com/24782682/113521472-efc2fb80-9599-11eb-98a9-4dca143dbe8d.jpg)

**Comment by soosp** [comment]
So, for me is should be enough to specify the topic generally for the node. Or sometimes it'd be useful if the node could pass the topic from it's input to it's output.

**Comment by DaveMDS** [comment]
I added an option to set the topic, indeed work well with the UI graph widget

Thanks for the suggestion :)
