### ISSUE TITLE
[FR] QoS and retain

### ISSUE THREAD

**Issue by hamster65** [DaveMDS/node-red-contrib-tasmota#23]
Hi,

is it possible to set qos and, more important to me, retain? My sonoff / tasmota wifi plugs are not always powered so I have to send out commands periodically. Having the retain function of mqtt, that should take care of that.

Thanks!

**Comment by DaveMDS** [comment]
This is already planned, will live in the next release

**Comment by hamster65** [comment]
Cool, thanks!

**Comment by DaveMDS** [comment]
This is now in GIT, a new release will come soon
