### ISSUE TITLE
Make a LWT status to enable/disable dashboard switch

### ISSUE THREAD

**Issue by RadioLed2000** [DaveMDS/node-red-contrib-tasmota#3]
Node-RED Dashboard buttons, switches etc can be enabled or disabled. For this you need to output  "msg.enabled" to true or false when LWT changes. The dasboard button will inactive when the device is powered off or lost wifi. Can you add this functionality please?

**Comment by DaveMDS** [comment]
Hi, I'm not sure this is the right way to make what you want, did you see any other nodes doing this? is this a common pattern in node-red?

**Comment by RadioLed2000** [comment]
My goal is to have clean interface with simple flows. See the screenshot. There is standart nodes, which I use now, in comparison with your node, if it will support sending LWT status. 
![lamp](https://user-images.githubusercontent.com/59708644/72210305-4db58000-34ca-11ea-9a9d-7d8cde96deac.JPG)

**Comment by DaveMDS** [comment]
Indeed my goal is the same as yours, I'm just searching for the cleanest way to implement this.

What I do not fully like about your proposal is that sending `msg.enabled` seems to me too much specific for the dashboard node you are using. If someone need the LWT for something else then this approach will not work. This is why I'm asking if you know of other nodes that do the same.

I can easily implement something generic, something like sending `msg.lwt` `Online/Offline`. This seems generic enough to me, but then you still need the Change node in the middle to adjust the msg.

...I'm still undecided, try to convince me :D

**Comment by RadioLed2000** [comment]
No. I don't know other nodes that do the same. You will be the first :)
If somebody need the LWT for sometheng else, he can use the Change mode to get the needed msg format from msg.enabled.
Or you can make settings to change what format of the LWT message user can see.
