### ISSUE TITLE
I am seeing this message quite a lot.

### ISSUE THREAD

**Issue by Just-another-pleb** [DaveMDS/node-red-contrib-tasmota#33]
`Error: read ECONNRESET`

And the weirder thing is that the node is disabled.

Sorry if this is too vague, but that's all I am seeing in the `debug` window at the side.

This is the best I can offer in the way of a screen shot.

![Screenshot from 2022-01-11 07-48-43](https://user-images.githubusercontent.com/39888280/148837426-fc146bce-345c-4d12-a4fc-ff2973f77992.png)

**Comment by DaveMDS** [comment]
Indeed this is too vague to give you a solution.
The error seems to be a disconnection from the mqtt broker.
Double check your broker config in nodered and look at the logs on your mqtt server

**Comment by Just-another-pleb** [comment]
Ok, thanks.

I guess I'll chalk it up to not solvable.

Luckily it isn't happening now, so....  It was something and now isn't.
