### ISSUE TITLE
Injects for 2 channels relay

### ISSUE THREAD

**Issue by S474N** [DaveMDS/node-red-contrib-tasmota#34]
Hi, is possible to add code examples to your screenshots?

Have Sonoff Dual R3 with two relays, but don't know, what must be in inject to control Relay 1 and Relay 2, as on this your screenshot:

![image](https://user-images.githubusercontent.com/16512337/161376344-9824b52b-eddc-41f7-9483-dd0146915d3e.png)

Thank you for reply.

**Comment by DaveMDS** [comment]
msg.topic: "switch1"
msg.payload: "Toggle"

as per the image ;)

**Comment by DaveMDS** [comment]
closing this for you ;D
