### ISSUE TITLE
"Input messages are NOT forwarded to the output." Except they are.

### ISSUE THREAD

**Issue by y8s** [DaveMDS/node-red-contrib-tasmota#35]
My Tasmota nodes are sending messages on the output when I control them via the input. 

The last line in the help text says they won't do this, but they do.

It's making my flows loop all over the place because they feed their output back to my source.

Was this changed at some point by accident?

node-red-contrib-tasmota 0.9.12
node red v2.2.2

**Comment by DaveMDS** [comment]
Hi,
I don't think this behavior changed and the node should not forward the input to the output.

Are you sure you are not seeing the messages received from the device? I mean: if you send, for example, a Toggle command to a node, you will then receive a message on the output that is the state change received from the device (not the same message you sent to the input)

**Comment by DaveMDS** [comment]
do you need help to fix your issue? if you explain your use case loop I can try to assist

**Comment by DaveMDS** [comment]
Yes, clear.
you simply don't have (and don't need) to connect nodes for the same device in row like you have done (otherwise you are explicitly creating loops). This is sure at least for the tasmota nodes, I cannot speak for the other ones.

The tasmota nodes are always (and automatically) in sync with the real state of the device, you don't have to send them a msg to update the internal state. You send a msg (command) to a tasmota device only when you want to control the device. And if you change the state from another source (google, HA, etc) the tasmota node will instantly change it's internal state to reflect the real state of the device, and will also generate a msg on the output so that you can (if needed) update other nodes in your flow.

really, don't connect nodes as you have done :)

**Comment by y8s** [comment]
To further expand on this, I'm not connecting the same device to itself, I'm connecting nodes for other services to each other. I understand that Tasmota nodes are in sync with the device/web interface and that's great. Same for Google Assistant, Kasa, Z2M, etc. I'm not suggesting wiring a node to itself to update its own status.

Here's an example image of what I'm trying to do: Let's say I have a light called "banana" and I use a zigbee button to turn it on and off. But I also use Google and HA. It might look like this:

![2022-05-27 (4)](https://user-images.githubusercontent.com/23405764/170720197-726817bb-29ff-4ee3-9262-ab64af5c14b9.png)

(nevermind that directly connecting this way doesn't always work, but I can fix that by changing payloads as necessary)

I simply want whatever receives the command from outside Node-RED to update the other node states appropriately so NR, Tasmota, Google, and HA all show the state correctly within a reasonable (short) amount of time after the command comes in.

Sometimes the nodes fight each other or google will send an update and HA will switch its toggle then revert back to the original state.  It's hard to characterize because I have several different combinations like this. Maybe the input is a Tasmota button, or zigbee2mqtt, or something else entirely from my flow.

**Comment by DaveMDS** [comment]
I don't know how the other nodes in your flow actually work...does the Goggle and the HA nodes directly control your light?
I mean: If you remove the wires from Google to Tasmota, is Google still able to turn on/off your light?

If this is the case I think that the only wire you need in this flow is the one from zigbee to Tasmota

**Comment by y8s** [comment]
The Google and HA nodes control the light, yes. So if I disconnect the Google node, for example, google home on my phone no longer has control (or gets state updates).

In other words, the HA and Google service have no other means of connecting to the Tasmota device outside of NodeRED.

For now, I've made a simple little flow that disables the output if a message came in to the input. Unfortunately I can't turn it into a subflow easily because the device node sits in the middle.

![image](https://user-images.githubusercontent.com/23405764/172418742-692a10d9-f0a2-4f1f-bc39-7f4ecceff2e3.png)

```
[{"id":"066c10578071cd11","type":"inject","z":"197925b7.eeffca","name":"From Other Service","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":1150,"y":320,"wires":[["2954b9ddbeac91ee"]]},{"id":"fc2cb74e9407b55d","type":"debug","z":"197925b7.eeffca","name":"To Other Service","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":1650,"y":320,"wires":[]},{"id":"82a0e8cbe3eb2f1a","type":"group","z":"197925b7.eeffca","name":"Anti Loop","style":{"stroke":"#4accd5","label":true,"color":"#000000","fill":"#4accd5","fill-opacity":"0.47"},"nodes":["c56fd785bdd37fc5","98995e54b54d3e97","518711e0f6727442","2954b9ddbeac91ee","ff05a3c4dc76c990"],"x":1254,"y":279,"w":282,"h":122},{"id":"c56fd785bdd37fc5","type":"trigger","z":"197925b7.eeffca","g":"82a0e8cbe3eb2f1a","name":"trig","op1":"","op2":"","op1type":"nul","op2type":"payl","duration":"250","extend":true,"overrideDelay":false,"units":"ms","reset":"","bytopic":"all","topic":"topic","outputs":1,"x":1495,"y":320,"wires":[["fc2cb74e9407b55d"]],"l":false},{"id":"98995e54b54d3e97","type":"change","z":"197925b7.eeffca","g":"82a0e8cbe3eb2f1a","name":"rst","rules":[{"t":"delete","p":"payload","pt":"msg"},{"t":"delete","p":"topic","pt":"msg"},{"t":"set","p":"reset","pt":"msg","to":"true","tot":"bool"}],"action":"","property":"","from":"","to":"","reg":false,"x":1425,"y":320,"wires":[["c56fd785bdd37fc5"]],"l":false},{"id":"518711e0f6727442","type":"delay","z":"197925b7.eeffca","g":"82a0e8cbe3eb2f1a","name":"dly","pauseType":"delay","timeout":"250","timeoutUnits":"milliseconds","rate":"1","nbRateUnits":"1","rateUnits":"second","randomFirst":"1","randomLast":"5","randomUnits":"seconds","drop":false,"allowrate":false,"outputs":1,"x":1365,"y":320,"wires":[["98995e54b54d3e97"]],"l":false},{"id":"2954b9ddbeac91ee","type":"function","z":"197925b7.eeffca","g":"82a0e8cbe3eb2f1a","name":":)","func":"\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":1295,"y":320,"wires":[["518711e0f6727442","ff05a3c4dc76c990"]],"icon":"node-red/arrow-in.svg","l":false},{"id":"ff05a3c4dc76c990","type":"Tasmota Light","z":"197925b7.eeffca","g":"82a0e8cbe3eb2f1a","broker":"8a2a6467.a65da8","device":"sasquatch","name":"Sasquatch","outputs":1,"uidisabler":false,"fullTopic":"","cmndPrefix":"","statPrefix":"","telePrefix":"","qos":1,"retain":false,"havedimmer":true,"havetemp":true,"havecolors":true,"tempformat":"K","colorsformat":"RGB","x":1400,"y":360,"wires":[["c56fd785bdd37fc5"]]},{"id":"8a2a6467.a65da8","type":"tasmota-mqtt-broker","name":"mqtt_broker","broker":"localhost","port":"1883","clientid":"","usetls":false,"keepalive":"60","cleansession":true}]
```
