### ISSUE TITLE
"close timed out" error when performing full deploy or modifying broker node

### ISSUE THREAD

**Issue by Mark-Muc** [DaveMDS/node-red-contrib-tasmota#36]
Hello .. since 3 day's I got the "close timed out" error when performing full deploy or modifying broker node
the MQTT Server seems to run in a timeout .. there is a similar problem 
here:
https://github.com/node-red/node-red/issues/2934#issuecomment-1150820847=
I've been told that i report it here.
cmd: 9 Jun 11:54:48 - [error] [tasmota-mqtt-broker:MyTas-MQTT] Error stopping node: Close timed out
Mark_Muc

**Comment by DaveMDS** [comment]
hi, what happened 3 days ago? did you upgraded something? what is changed?

**Comment by DaveMDS** [comment]
I never saw this error in my setup, any idea on how to reproduce?

**Comment by Mark-Muc** [comment]
not really  .. sorry for answering so late . i saved may flowes .. setup node.red 3.0.1 and the error was gone .. but again thx fpr looking into it
Mark
