### ISSUE TITLE
Power "blink" option

### ISSUE THREAD

**Issue by OneHoopyFrood** [DaveMDS/node-red-contrib-tasmota#37]
Tasmota supports sending a "blink" message to the power cmnd channel of a device. I use this to indicate to my daughter that her light will be turning off for bedtime in 5 minutes.

"blink" should be a valid input for on/state/power and should send the message "blink" to the cmnd channel.

Currently, this can be done as shown in the README by issuing a msg.topic "command" with the msg.payload set to "Power blink". While an acceptable work-around, I do feel the blink option should be directly supported, similar to "toggle."

**Comment by DaveMDS** [comment]
Hi, indeed this can be a useful feature for the light and the switch nodes.
Are you able to provide a pull request that implement this?

**Comment by OneHoopyFrood** [comment]
I am. I'll work on it when I have some spare time. Could be awhile, but I'm happy to do it.

**Comment by DaveMDS** [comment]
Great :)
