### ISSUE TITLE
Devices show "Offline" when referenced in multiple flows

### ISSUE THREAD

**Issue by OneHoopyFrood** [DaveMDS/node-red-contrib-tasmota#39]
I'm not sure if this is fixable, but when multiple tasmota nodes reference the same device name (disclaimer: only tried with lights) only one of them shows the correct state. The others (somewhat random order, assume it's based on a race condition) show "Offline" or occasionally "Wrong Config" (only until a message is sent, then it switches to "offline").

To illustrate, these are in two separate flows:

![Screen Shot 2022-08-03 at 11 03 24 AM](https://user-images.githubusercontent.com/3092695/182656065-f142f64c-2b3e-4051-aa2f-66b973c818d3.png)

![Screen Shot 2022-08-03 at 11 03 32 AM](https://user-images.githubusercontent.com/3092695/182656054-cbc68e96-19ed-4fd9-8d2a-8ff006963a99.png)

It would be preferred that all references were able to show the status correctly.

**Comment by DaveMDS** [comment]
Hi,
I'm not able to reproduce this error, please double check the broker config of your nodes.
Both nodes (in same or different flows) should use the same broker configuration item. In general you should have a single broker config for all your tasmota nodes (so a single connection to the broker is made and shared across nodes)

**Comment by OneHoopyFrood** [comment]
Interesting.

These are actually copied directly from one to another between flows. I'm not on my network right now but I'll check the configs when I'm back home. It does seem somewhat inconsistent about which flow fails, leading to my suspicion of some form of race condition.

For context, I'm running a mosquito service on localhost. Nothing special.

If I can reproduce consistently I'll send you a minimal example.

**Comment by OneHoopyFrood** [comment]
So it seems to be only occurring after MQTT messages are sent to the lights via some other method, such as from an app. Then whichever flow you're in when it happens gets the "offline" state except the last remaining.

**Comment by DaveMDS** [comment]
Still not able to reproduce :/

Have a light node in 2 different flows, issuing a power toggle command from an external app (MQTT explorer), and everything works as expected.

Try to look at your mosquitto logs, maybe there is something interesting there. 

Also make sure you are not using the same client-id for NodeRed and the other apps (client-id should be unique for each app that connect to the broker)

**Comment by FreekBos** [comment]
Hi, I have exacly the same behavior: no matter what I do, I don't get nodes to connect to the broker.
The buildin mqtt nodes register fine (63 nodes), zigbee2mqtt (37) registers fine but I can't make node-red-tasmota to work.
Can I provide any info to assist?
- ubuntu: 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
- node-red 3.0.2
- mqtt mosquitto version 2.0.14
Many thanks in advance

**Comment by DaveMDS** [comment]
I need to see the configuration for the tasmota-mqtt-broker (that do not work) and the nodered mqtt-broker (that works), I also need to see the configuration for an mqtt node and a tasmota node.

You should get some kind of errors, in the nodered debug panel, in nodered console or in the mosquitto logs

**Comment by FreekBos** [comment]
Will look for logging in NR / MQTT - sofar nothing.
KR,
F
[tasmota mqtt - that doesnt work.zip](https://github.com/DaveMDS/node-red-contrib-tasmota/files/9484742/tasmota.mqtt.-.that.doesnt.work.zip)
[nr mqtt - that does work.zip](https://github.com/DaveMDS/node-red-contrib-tasmota/files/9484743/nr.mqtt.-.that.does.work.zip)
[tasmo.zip](https://github.com/DaveMDS/node-red-contrib-tasmota/files/9484770/tasmo.zip)

**Comment by DaveMDS** [comment]
Hi, the first thing that I see in your config is the "Device" field in the tasmota node config: 
it should match the "Topic" field in your tasmota device config, not the full topic. But you are using a quite custom naming convention for your devices, so it's not easy to say. Can you show me the MQTT config page on the tasmota device itself?

**Comment by DaveMDS** [comment]
Ok, then you need to configure the tasmota node as: 
`lamp04` in the `Device` field 
`h13/son/bg/light/%topic%/%prefix%/` in the `Full Topic` field (in the advanced tab)

**Comment by DaveMDS** [comment]
I also added a section in the README to explain the various configuration values.
In the screenshots I left your FullTopic values as I was testing them, hope you don't mind, otherwise let me know and I will remake the screenshots with a bit more privacy ;)

**Comment by FreekBos** [comment]
Ha Dave,
Just tested it... works well! 
Thank you ever so much

**Comment by DaveMDS** [comment]
@FreekBos great :)
