### ISSUE TITLE
quiet tasmota nodes on flow deploy

### ISSUE THREAD

**Issue by brjhaverkamp** [DaveMDS/node-red-contrib-tasmota#41]
Hi, I noticed the Tasmota nodes send a message with their current status when you press deploy in node red.
However this triggers (at least in my case) logic in other nodes to start doing things. Resulting in flashing lights in the house whenever I press deploy.
Can we have an option to "silence" this behaviour?

**Comment by DaveMDS** [comment]
Hi,
the "emit updated state every time is needed" is one of the core feature of the Tasmota Nodes.
Disabling that feature means that your flows will be out-of-sync with the "real world" when they startup or restart,
es: your light is ON, you shutdown nodered, you turn OFF the light, then you restart nodered. At this point you cannot know what is the state of the light in your flow!

I highly suggest you to adjust your flows to not make random stuff at startup :)
