### ISSUE TITLE
switch node channels

### ISSUE THREAD

**Issue by Mark-Muc** [DaveMDS/node-red-contrib-tasmota#47]
Hello ... first of all, thank you for the nice and good working  tasmota nodes.
I do now have a relay board supporting 16 channels .. Tasmota 
New versions of Tasmota support more then 8 relays now ..
Is it possible that the switch node supports more than 8 channels?
The device will show correctly and working but output channels work only up to 8 channels ..
I can split myself using a function (1 channel or all merged) node .. but will be much easiest if the switch node 
will support it by default!!
THX & Regards
Mark_Muc
![image](https://github.com/DaveMDS/node-red-contrib-tasmota/assets/67410847/ac4f440b-b5ad-4868-8e29-ba52950358fb)

**Comment by DaveMDS** [comment]
Hi,
up to 48 channels implemented in 83b20ee

**Comment by Mark-Muc** [comment]
Hey thank you ... didn't expect it . but it's nice to have ...
Regards
Mark_Muc
