### ISSUE TITLE
tasmota sensor node with multi outputs gives warning with node-red version 3.1.0 (Sept. 2023)

### ISSUE THREAD

**Issue by schwonko-git** [DaveMDS/node-red-contrib-tasmota#49]
Sensor node with one payload output works as before,
but when splitting the output data by some Jasonata expressions, it still works,
but produces the warning (with debug dump of stack) :  __"Jasonata without callback no longer valid at Node-red 4.0".__
The exact warning text is:
"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."
So the sensor node should be updated in time.

**Comment by exotsk** [comment]
i have the same error

**Comment by predecker** [comment]
same here.

**Comment by oldironUK** [comment]
Hopefully this helps:

"Deprecated API warning: Calls to RED.util.evaluateJSONataExpression must include a callback. This will not be optional in Node-RED 4.0. Please identify the node from the following stack and check for an update on npm. If none is available, please notify the node author."

> Error
    at Object.evaluateJSONataExpression (/usr/src/node-red/node_modules/@node-red/util/lib/util.js:775:18)
    at TasmotaSensorNode.sendToOutputs (/data/node_modules/node-red-contrib-tasmota/nodes/sensor.js:50:35)
    at TasmotaSensorNode.onSensorStatus (/data/node_modules/node-red-contrib-tasmota/nodes/sensor.js:70:14)
    at /data/node_modules/node-red-contrib-tasmota/nodes/sensor.js:21:14
    at MqttClient.<anonymous> (/data/node_modules/node-red-contrib-tasmota/nodes/mqtt_broker.js:113:21)

thanks

**Comment by DaveMDS** [comment]
Fixed in commit e70ba30

Thanks for reporting guys
