### ISSUE TITLE
Sensor node emits all topics

### ISSUE THREAD

**Issue by tablatronix** [DaveMDS/node-red-contrib-tasmota#50]
I have a sensor node, with just device id set.

I expect to see tele/X/sensor/

I see all topics instead ( at least on the first payload channel )

![Screenshot 2023-09-12 at 9 55 16 PM](https://github.com/DaveMDS/node-red-contrib-tasmota/assets/807787/7dfc6771-db1d-47ae-94f5-cbb3ae66c4c3)
![Screenshot 2023-09-12 at 9 55 04 PM](https://github.com/DaveMDS/node-red-contrib-tasmota/assets/807787/d2d5307c-7074-4239-92e3-ad9e3c855936)

**Comment by tablatronix** [comment]
Workaround: I shunt channel 1

**Comment by DaveMDS** [comment]
This is strange, I cannot reproduce here

What is really strange is the topic you receive in your DEBUG nodes, you should only see the messages with topic `sensor/pool/temperature`, all the other ones are extraneous and I cannot see how that can be sent by the tasmota node.

Seems something else is confusing the node, can you dig a bit further?

**Comment by tablatronix** [comment]
Yeah I will revisit and check again

**Comment by tablatronix** [comment]
Not seeing it anymore, checked the same flow, and created a new test suite.
I have updated nodered since then also.

Closing

**Comment by DaveMDS** [comment]
great, thanks
