### ISSUE TITLE
Nodes not saving settings correctly

### ISSUE THREAD

**Issue by fetuffani** [DaveMDS/node-red-contrib-tasmota#52]
NodeRED version: v3.1.3
Tasmota nodes version: 0.9.13

When you place a node (tested with Switch)  some settings like QoS and Retain will default to `1` (integer) and `false` (boolean) as defined in the [switch.html line 182](https://github.com/DaveMDS/node-red-contrib-tasmota/blob/1f7fe674853f5d013e37ed34cdbc57347b010757/nodes/switch.html#L182) and in the [base_tasmota.js line 15](https://github.com/DaveMDS/node-red-contrib-tasmota/blob/1f7fe674853f5d013e37ed34cdbc57347b010757/nodes/base_tasmota.js#L15C10-L15C10)

When you modify the QoS to zero, internally it will save the QoS setting (in the NodeRED flows.json file)  as `"0"`, as a **string** and not an **integer** anymore, this prevents the node from connecting to the MQTT broker and remains offline indefinitely. (maybe there is an internal crash when parsing the setting and the offline is a false message as I received many timeout messages)

When you change the Retain to `true` or `false`, it will save the setting as `"true"` or `"false"` both as **string** and not **boolean** anymore.
This does not prevents the node from connecting to the MQTT broker but every message is sent as retained even with the `"false"` setting as `"false"` string is interpreted as `true` boolean

Not tested with other nodes or settings

![settings](https://github.com/DaveMDS/node-red-contrib-tasmota/assets/8229714/14c8345c-7908-4475-b956-7faff546342e)

**Comment by DaveMDS** [comment]
Thanks for reporting this
