### ISSUE TITLE
unable to get tasmota to connect to sensor node 

### ISSUE THREAD

**Issue by ggrobi** [DaveMDS/node-red-contrib-tasmota#8]
Am I not sure how the setup needs to be? do I point MQTT on the tasmota to the node-red server and if so what ports.  I am new to Node-red and I have an MQTT broker taking between an esp8266/ dht11 and node-red server working. I wanted to try your software but can't find the details to get it working. Any help would be useful

**Comment by DaveMDS** [comment]
Sorry, but I really cannot understand your problem... please explain with more details and maybe some images

MQTT config on the tasmota device must point to your MQTT broker.
Config on the tasmota node in node-red must point to your MQTT broker.

**Comment by ggrobi** [comment]
I understand, it still needs the broker in between.  I wasn't able to get it to connect and pass on the messages as with the standard MQTT node. So I thought it might need to communicate directly with the Tasmota device. As I said I'm new to node-red and just finding my way around. What makes this different from the standards MQTT components? I don't know enough about each type to judge the merits of either. Thanks for the info.
cheers
Gary

**Comment by DaveMDS** [comment]
To use the standard MQTT node you need to know the "protocol" that tasmota implement over mqtt, you need to know where and how it publish things and you need to know what message to send to control your tasmota device.
Using the tasmota nodes instead you get a plug-and-play experience, without the need to know anything about the protocol. It is just usefull to make your life easier :)

**Comment by ggrobi** [comment]
Thanks for the reply, is there as step by step guide or details examples? I've looked at the web page node-red and git but can't seem to find detailed info.
cheers
Gary

**Comment by DaveMDS** [comment]
no, there are no other docs for this nodes, but the config should be quite strightforward, and the images in the github pages show how you can use the nodes.
To make a sensor node to work you just need two things in the node config: your broker connection (the same you have done for the standard MQTT node) and the name/id of your tasmota device. thats all
